In [9]:
import numpy as np
import pandas as pd

## Load data from a csv  file

a csv file contains comma-separated values (CSV) <br>
https://en.wikipedia.org/wiki/Comma-separated_values

In [10]:
df = pd.read_csv('patient_record.csv', sep=',')
df

Age Sex  Tumor_size_mm
0   30   M            1.0
1   40   F            2.0
2   85   F            0.1
3   75   M            1.0
4   95   F            3.0

In [11]:
df.shape

(5, 3)

In [12]:
df.columns # column indexes

Index(['Age', 'Sex', 'Tumor_size_mm'], dtype='object')

In [13]:
df.index  # row indexes

RangeIndex(start=0, stop=5, step=1)

In [14]:
df.iloc[0,:] # the first row, data type is Series

Age               30
Sex                M
Tumor_size_mm    1.0
Name: 0, dtype: object

In [15]:
type(df.iloc[0,:])

pandas.core.series.Series

In [16]:
df.iloc[0:1,:] # the first row, data type is dataframe

Age Sex  Tumor_size_mm
0   30   M            1.0

In [17]:
type(df.iloc[0:1,:])

pandas.core.frame.DataFrame

### add a new column to the dataframe

In [18]:
df['smoking'] = [0, 1, 7, 1, 0]
#0: never smoke cigarettes
#1: 1 day per week
#7: everyday (7 days per week)
df

Age Sex  Tumor_size_mm  smoking
0   30   M            1.0        0
1   40   F            2.0        1
2   85   F            0.1        7
3   75   M            1.0        1
4   95   F            3.0        0

In [19]:
df=df.append({'Age':50.0, 'Sex':'F', 'Tumor_size_mm':1.0, 'smoking':7},ignore_index=True)
df

/var/folders/tj/rfh5llcj025989b4_l8zp5bc0000gn/T/ipykernel_22635/2084623629.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append({'Age':50.0, 'Sex':'F', 'Tumor_size_mm':1.0, 'smoking':7},ignore_index=True)


Age Sex  Tumor_size_mm  smoking
0  30.0   M            1.0        0
1  40.0   F            2.0        1
2  85.0   F            0.1        7
3  75.0   M            1.0        1
4  95.0   F            3.0        0
5  50.0   F            1.0        7

In [20]:
df['height'] = [1.6, 1.7, 1.8, 1.5, 1.9] # unit: meter
df['weight'] = [60, 70, 80, 50, 90] # unit:kg
df

ValueError: Length of values (5) does not match length of index (6)

In [ ]:
# BMI (Body mass index) = weight /(height*height)
df['BMI'] = df['weight']/df['height']**2
df

In [21]:
df[['Age', 'BMI']] # select two columns

KeyError: "['BMI'] not in index"

convert the two columns 'Age' & 'BMI' to a Numpy array

In [22]:
df[['Age', 'BMI']].values

KeyError: "['BMI'] not in index"

### Save the new data to a csv file

In [23]:
#save the new Dataframe df_new to a csv file
#set index=False, so the row indexes will not be saved  
df.to_csv('patient_record_new.csv', index=False, sep=',')

## Combine two Series objects

In [24]:
s1 = pd.Series(['A', 'B', 'C'], index=[0, 1, 2])
s2 = pd.Series(['D', 'E', 'F'], index=[3, 4, 5])
s12=pd.concat([s1, s2])
s12

0    A
1    B
2    C
3    D
4    E
5    F
dtype: object

In [25]:
# if we do not set index ..
s1 = pd.Series(['A', 'B', 'C'])
s2 = pd.Series(['D', 'E', 'F'])
s12=pd.concat([s1, s2])
s12

0    A
1    B
2    C
0    D
1    E
2    F
dtype: object

In [26]:
s12[0] # an index -> two values, this is weird...

0    A
0    D
dtype: object

## Combine Two Dataframe Objects

In [27]:
Matrix = [[1, 2],
          [3, 4],
          [5, 6]]
df1 = pd.DataFrame(Matrix, columns=['A', 'B'], index=[0, 1, 2]) 
df2 = pd.DataFrame(Matrix, columns=['C', 'D'], index=[3, 4, 5]) 
df12=pd.concat([df1, df2], axis=0)
df12

A    B    C    D
0  1.0  2.0  NaN  NaN
1  3.0  4.0  NaN  NaN
2  5.0  6.0  NaN  NaN
3  NaN  NaN  1.0  2.0
4  NaN  NaN  3.0  4.0
5  NaN  NaN  5.0  6.0

In [28]:
Matrix = [[1, 2],
          [3, 4],
          [5, 6]]
# both df1 and df2 have the column index 'A'
df1 = pd.DataFrame(Matrix, columns=['A', 'B'], index=[0, 1, 2]) 
df2 = pd.DataFrame(Matrix, columns=['A', 'D'], index=[3, 4, 5]) 
df12=pd.concat([df1, df2], axis=0)
df12

A    B    D
0  1  2.0  NaN
1  3  4.0  NaN
2  5  6.0  NaN
3  1  NaN  2.0
4  3  NaN  4.0
5  5  NaN  6.0

In [29]:
Matrix = [[1, 2],
          [3, 4],
          [5, 6]]
# both df1 and df2 have the the row index 0
df1 = pd.DataFrame(Matrix, columns=['A', 'B'], index=[0, 1, 2]) 
df2 = pd.DataFrame(Matrix, columns=['C', 'D'], index=[0, 4, 5]) 
df12=pd.concat([df1, df2], axis=0)
df12

A    B    C    D
0  1.0  2.0  NaN  NaN
1  3.0  4.0  NaN  NaN
2  5.0  6.0  NaN  NaN
0  NaN  NaN  1.0  2.0
4  NaN  NaN  3.0  4.0
5  NaN  NaN  5.0  6.0

the above dataframe is weird ...
two rows have the same the row index

### Merge two dataframe objects using `pd.merge`
if some row/column indexes of two dataframes are the same, it is better to use the function pd.merge

In [30]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [31]:
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'], 
                    'hire_date': [2004, 2008, 2012, 2014]})
df2

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [32]:
df3 = pd.merge(df1, df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [33]:
df_weird = pd.concat([df1, df2], axis=0, sort=False)
df_weird

employee        group  hire_date
0      Bob   Accounting        NaN
1     Jake  Engineering        NaN
2     Lisa  Engineering        NaN
3      Sue           HR        NaN
0     Lisa          NaN     2004.0
1      Bob          NaN     2008.0
2     Jake          NaN     2012.0
3      Sue          NaN     2014.0

In [34]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
df4 

group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [35]:
df3 # df3 is pd.merge(df1, df2)

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

df3 and df4 have the column index 'group' <br>
the 'group' columns in df3 an df4 are called key-columns  <br>
pandas will merge df3 an df4 by the key-columns

In [36]:
df34 = pd.merge(df3, df4)
df34

employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

## Handle Missing Data

`None` is used a placeholder of missing data/object

In [37]:
A = np.array([0, None, 2, 3], dtype='object')
A

array([0, None, 2, 3], dtype=object)

In [38]:
print(A[1]) # the value is missing

None


In [39]:
# try to compute the sum
A.sum() # error!

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

`nan` is used to represent a numerical missing value <br>
type of `nan` is float

In [40]:
A = np.array([0, np.nan, 2, 3], dtype='float64')
A

array([ 0., nan,  2.,  3.])

In [41]:
A.sum()

nan

In [42]:
1 + np.nan

nan

In [43]:
10 * np.nan

nan

### Handle none and nan in Series

In [44]:
ser= pd.Series([1, np.nan, 'hello', None])
ser

0        1
1      NaN
2    hello
3     None
dtype: object

In [45]:
ser.isnull() # null refers to nan and None

0    False
1     True
2    False
3     True
dtype: bool

In [46]:
ser.notnull()

0     True
1    False
2     True
3    False
dtype: bool

remove nan and None from the Series

In [47]:
ser[ser.notnull()]

0        1
2    hello
dtype: object

If a Series only contains numerical data, we can convert it to array, <br> then handle missing data using Numpy functions

In [48]:
arr = pd.Series([0, np.nan, None, 1, 100])
arr = arr.values # None -> nan
arr

array([  0.,  nan,  nan,   1., 100.])

In [49]:
arr.dtype

dtype('float64')

In [50]:
np.isnan(arr)

array([False,  True,  True, False, False])

In [51]:
# np.is_not_nan
~np.isnan(arr) # the tilde symbol/operator performs logical not

array([ True, False, False,  True,  True])

remove nan from the array

In [52]:
arr[~np.isnan(arr)]

array([  0.,   1., 100.])

#### Find and Replace none and nan in Series

In [53]:
ser= pd.Series([1, np.nan, 'hello', None])
ser[ser.isnull()] = 'nothing'
ser

0          1
1    nothing
2      hello
3    nothing
dtype: object

In [54]:
# If a Series only contains numerical data, we can convert it to array
# then handle missing data using Numpy functions
ser = pd.Series([0, np.nan, None, 1, 100])
arr = ser.values
print(type(arr))
arr

<class 'numpy.ndarray'>


array([  0.,  nan,  nan,   1., 100.])

In [55]:
# repalce nan with 0 (or other number)
arr[np.isnan(arr)]= 0
arr

array([  0.,   0.,   0.,   1., 100.])

## Handle nan in DataFrame

In [56]:
df = pd.read_csv('patient_record_missing_data.csv', sep=',')
#null -> nana, open the file in a text editor
df

Age  Sex  Tumor_size_mm
0  30.0  NaN            1.0
1  40.0    F            2.0
2  85.0    F            0.1
3  75.0    M            1.0
4   NaN    F            3.0

Suppose that we are developing a machine learning algorithm that will predict the outcome of brain tumor surgery based on Age and Sex <br>
<br>
First, we need to find the rows that have missing data

In [57]:
#check if a number is nan
x = np.nan
print(x == np.nan)

False


nan is not equal to nan

In [58]:
#check if a number is nan
x = np.nan
np.isnan(x)
df.shape[0]

5

In [59]:
# write a program to find the rows with missing data (nan and None)
bad_row_index_list=[]
test_array=[1]
for n in range(0, df.shape[0]):
    row=df.iloc[n,:].isnull().values
    if df.iloc[n,1]
    row = df.iloc[n,:]
    if np.any(row==True):
        bad_row_index_list.append(n)
bad_row_index_list

[0, 4]

How should we handle the data of the patient-0 (row-0) and patient-4(row-4) ?


In [60]:
#we could remove all of the 'bad' rows
df_clean = df.drop(bad_row_index_list, axis=0)
df_clean

Age Sex  Tumor_size_mm
1  40.0   F            2.0
2  85.0   F            0.1
3  75.0   M            1.0

In [61]:
#we could modify some of the 'bad' rows
row = df.iloc[4,:]
row

Age              NaN
Sex                F
Tumor_size_mm    3.0
Name: 4, dtype: object

In [62]:
row['Age']= 75 # replace nan with the average age

/var/folders/tj/rfh5llcj025989b4_l8zp5bc0000gn/T/ipykernel_22635/862720678.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  row['Age']= 75 # replace nan with the average age


In [63]:
df.iloc[4,:]=row
df

Age  Sex  Tumor_size_mm
0  30.0  NaN            1.0
1  40.0    F            2.0
2  85.0    F            0.1
3  75.0    M            1.0
4  75.0    F            3.0

In [64]:
df_clean=df.drop(0, axis=0) # remove the first row
df_clean

Age Sex  Tumor_size_mm
1  40.0   F            2.0
2  85.0   F            0.1
3  75.0   M            1.0
4  75.0   F            3.0

Now, the data is clean and ready for machine learning